<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="stl27l_sensor" params="
    prefix:=''
    parent:='base_link'
    frame_id:='stl27l_link'
    mesh_file:='$(find antbot_description)/meshes/stl27l.dae'
    xyz_offset:='0 0 1.0'
    rpy_offset:='0 0 0'
    mesh_xyz_offset:='0 0 0'
    mesh_rpy_offset:='${-M_PI/2} 0 0'
    mesh_scale:='1 1 1'
    collision_xyz_offset:='0 0 0'
    collision_rpy_offset:='0 0 0'
    inertial_xyz_offset:='0 0 0'
    inertial_rpy_offset:='0 0 0'
    lidar_width:=0.04629
    lidar_height:=0.0348
    mass:=0.0461
    update_rate:=10
    ray_count:=360
    noise_stddev:=0.003
    min_angle:='-1.5707963268'
    max_angle:='1.5707963268'
    min_range:='0.4'
    max_range:='25.0'
    range_resolution:='0.034906585'
    topic_name:='scan_stl27l'
    always_on:=true
    visualize:=false
    enable_collision:=false">

    <xacro:property name="radius" value="${lidar_width/2}" />
    <xacro:property name="ixx_iyy" value="${(mass/12) * (3 * radius * radius + lidar_height * lidar_height)}" />
    <xacro:property name="izz" value="${(mass/2) * (radius * radius)}" />

    <link name="${prefix}${frame_id}">
      <visual>
        <origin xyz="${mesh_xyz_offset}" rpy="${mesh_rpy_offset}"/>
        <geometry>
          <mesh filename="file://${mesh_file}" scale="${mesh_scale}"/>
        </geometry>
      </visual>

      <xacro:if value="${enable_collision}">
        <collision>
          <origin xyz="${collision_xyz_offset}" rpy="${collision_rpy_offset}"/>
          <geometry>
            <mesh filename="file://${mesh_file}" scale="${mesh_scale}"/>
          </geometry>          
        </collision>
      </xacro:if>

      <inertial>
        <mass value="${mass}" />
        <origin xyz="${inertial_xyz_offset}" rpy="${inertial_rpy_offset}"/>
        <inertia
          ixx="${ixx_iyy}"
          ixy="0.0"
          ixz="0.0"
          iyy="${ixx_iyy}"
          iyz="0.0"
          izz="${izz}" />
      </inertial>
    </link>

    <joint name="${prefix}${frame_id}_joint" type="fixed">
      <parent link="${prefix}${parent}"/>
      <child link="${prefix}${frame_id}" />
      <origin xyz="${xyz_offset}" rpy="${rpy_offset}"/>
    </joint>

    <gazebo reference="${prefix}${frame_id}">
      <sensor name="${prefix}stl27l_sensor" type="gpu_lidar">
        <topic>${topic_name}</topic>
        <update_rate>${update_rate}</update_rate>
        <always_on>${always_on}</always_on>
        <visualize>${visualize}</visualize>
        <lidar>
          <scan>
            <horizontal>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
            <vertical>
              <samples>32</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>${range_resolution}</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>${noise_stddev}</stddev>
          </noise>
        </lidar>
        <gz_frame_id>${prefix}${frame_id}</gz_frame_id>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
